"""Analyze three-expert win rates by age-gap bins and plot a 100% stacked bar chart.

This script reads the inference CSV generated by
`ECAPA-TDNN_inference_three_experts.py`, groups pairs by age-gap bins,
and visualizes how often each expert wins inside each bin.

Tie rows are excluded from the percentage denominator so that each bar
represents the distribution among the three experts only.
"""

from __future__ import annotations

import argparse
from pathlib import Path

import matplotlib as mpl
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd


mpl.rcParams["font.sans-serif"] = [
    "Microsoft JhengHei",
    "Microsoft YaHei",
    "Noto Sans CJK TC",
    "Noto Sans CJK SC",
    "SimHei",
    "DejaVu Sans",
]
mpl.rcParams["axes.unicode_minus"] = False


DEFAULT_INPUT_CSV = Path("logs") / "ecapa_tdnn_lora" / "three_expert_inference" / "Vox-merge_three_expert_scores.csv"
DEFAULT_OUTPUT_PLOT = Path("logs") / "ecapa_tdnn_lora" / "three_expert_inference" / "Vox-merge_three_expert_age_gap_winrate.png"
DEFAULT_OUTPUT_SUMMARY = Path("logs") / "ecapa_tdnn_lora" / "three_expert_inference" / "Vox-merge_three_expert_age_gap_winrate_summary.csv"

AGE_GAP_BIN_LABELS = ["0-5", "5-10", "10-15", ">15"]
EXPERT_COLUMNS = ["expert_1", "expert_2", "expert_3"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Plot three-expert win rates by age-gap bins from inference CSV."
    )
    parser.add_argument(
        "--input-csv",
        type=Path,
        default=DEFAULT_INPUT_CSV,
        help="Path to the inference CSV file.",
    )
    parser.add_argument(
        "--output-plot",
        type=Path,
        default=DEFAULT_OUTPUT_PLOT,
        help="Path to save the stacked bar chart.",
    )
    parser.add_argument(
        "--output-summary",
        type=Path,
        default=DEFAULT_OUTPUT_SUMMARY,
        help="Path to save the summary CSV.",
    )
    return parser.parse_args()


def load_inference_csv(csv_path: Path) -> pd.DataFrame:
    if not csv_path.exists():
        raise FileNotFoundError(f"Input CSV not found: {csv_path}")

    df = pd.read_csv(csv_path)
    required_columns = {"age_gap_year", "winner", "is_same"}
    missing_columns = required_columns.difference(df.columns)
    if missing_columns:
        raise ValueError(f"Missing required columns: {sorted(missing_columns)}")

    df = df.copy()
    df["age_gap_year"] = pd.to_numeric(df["age_gap_year"], errors="coerce")
    # keep is_same as integer 0/1 when possible
    if "is_same" in df.columns:
        df["is_same"] = pd.to_numeric(df["is_same"], errors="coerce").fillna(0).astype(int)
    df["winner"] = df["winner"].astype(str).str.strip()
    df = df.dropna(subset=["age_gap_year"])
    return df


def assign_age_gap_bins(df: pd.DataFrame) -> pd.DataFrame:
    bins = [0, 5, 10, 15, np.inf]
    df = df.copy()
    df["age_gap_bin"] = pd.cut(
        df["age_gap_year"],
        bins=bins,
        labels=AGE_GAP_BIN_LABELS,
        include_lowest=True,
        right=True,
    )
    return df


def build_summary_table(df: pd.DataFrame) -> pd.DataFrame:
    valid = df[df["winner"].isin(EXPERT_COLUMNS)].copy()

    counts = (
        valid.groupby(["age_gap_bin", "winner"], observed=False)
        .size()
        .unstack(fill_value=0)
        .reindex(index=AGE_GAP_BIN_LABELS, columns=EXPERT_COLUMNS, fill_value=0)
    )

    totals = counts.sum(axis=1)
    percentages = counts.div(totals.replace(0, np.nan), axis=0).fillna(0.0) * 100.0

    summary = percentages
    summary.insert(0, "expert_win_total", totals.astype(int))

    bin_totals = df.groupby("age_gap_bin", observed=False).size().reindex(AGE_GAP_BIN_LABELS, fill_value=0)
    tie_counts = (
        df[~df["winner"].isin(EXPERT_COLUMNS)]
        .groupby("age_gap_bin", observed=False)
        .size()
        .reindex(AGE_GAP_BIN_LABELS, fill_value=0)
    )
    summary.insert(0, "pair_total", bin_totals.astype(int))
    summary.insert(2, "tie_total", tie_counts.astype(int))

    return summary


def plot_summary(summary: pd.DataFrame, output_plot: Path, title: str) -> None:
    output_plot.parent.mkdir(parents=True, exist_ok=True)

    x = np.arange(len(summary.index))
    # do not shift bars here; we'll move the axes instead so legend can sit inside
    shift = 0.0
    x_pos = x + shift
    # reduce bar width so bars appear slimmer
    width = 0.45
    colors = ["#1f77b4", "#ff7f0e", "#2ca02c"]

    fig, ax = plt.subplots(figsize=(10, 6))
    bottom = np.zeros(len(summary.index), dtype=float)
    all_bars = []

    for idx, expert in enumerate(EXPERT_COLUMNS):
        values = summary[expert].to_numpy(dtype=float)
        bars = ax.bar(
            x_pos,
            values,
            width=width,
            bottom=bottom,
            color=colors[idx],
            edgecolor="white",
            linewidth=1.0,
            label=expert.replace("_", " ").title(),
        )
        # collect individual bar patches for overlap checking
        all_bars.extend(list(bars))

        for bar, value, base in zip(bars, values, bottom):
            if value < 4.0:
                continue
            ax.text(
                bar.get_x() + bar.get_width() / 2.0,
                base + value / 2.0,
                f"{value:.1f}%",
                ha="center",
                va="center",
                fontsize=9,
                color="white",
                fontweight="bold",
            )

        bottom += values

    ax.set_xticks(x_pos)
    ax.set_xticklabels(summary.index.tolist(), fontsize=11)
    ax.set_ylim(0, 112)
    ax.set_ylabel("Win rate (%)", fontsize=12)
    ax.set_xlabel("Age-gap bin", fontsize=12)
    ax.set_title(title, fontsize=14, fontweight="bold")
    ax.grid(axis="y", linestyle=":", alpha=0.35)
    # keep default axes position (no left/right shifting)

    # place legend inside axes at top-right (axes-relative coordinates)
    legend = ax.legend(loc="upper right", bbox_to_anchor=(0.95, 0.95), bbox_transform=ax.transAxes, frameon=True, prop={"size": 9})

    # ensure all spines are visible and draw a clean box around the axes
    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_linewidth(1.0)
        spine.set_color("black")

    # draw a rectangle that frames the axes area (in axes coordinates)
    rect = mpl.patches.Rectangle((0, 0), 1, 1, transform=ax.transAxes, fill=False, linewidth=1.0, edgecolor="black", clip_on=False)
    ax.add_patch(rect)

    for xpos, total, tie_total in zip(x_pos, summary["pair_total"], summary["tie_total"]):
        ax.text(
            xpos,
            101.5,
            f"n={int(total)}\ntie={int(tie_total)}",
            ha="center",
            va="bottom",
            fontsize=9,
            clip_on=False,
        )

    fig.tight_layout()
    fig.savefig(output_plot, dpi=200, bbox_inches="tight")
    plt.close(fig)


def main() -> None:
    args = parse_args()

    df = load_inference_csv(args.input_csv)
    df = assign_age_gap_bins(df)

    # overall summary (unchanged)
    summary = build_summary_table(df)
    summary_to_save = summary.copy()
    summary_to_save[EXPERT_COLUMNS] = summary_to_save[EXPERT_COLUMNS].round(2)

    # do not save CSV summaries; keep only plots

    # create positive / negative subsets and summaries
    df_pos = df[df["is_same"] == 1]
    df_neg = df[df["is_same"] == 0]

    summary_pos = build_summary_table(df_pos)
    summary_neg = build_summary_table(df_neg)

    # do not save per-split CSV summaries

    print(f"Loaded {len(df):,} rows from {args.input_csv}")
    print(f"Age-gap bins: {', '.join(AGE_GAP_BIN_LABELS)}")
    print(f"Total pairs (overall): {int(summary['pair_total'].sum()):,}")
    print(f"Total pairs (positive): {int(summary_pos['pair_total'].sum()):,}")
    print(f"Total pairs (negative): {int(summary_neg['pair_total'].sum()):,}")

    title = "Three-expert win rate by age-gap bin"
    # one plot per summary (no left/right variants)
    out_overall = args.output_plot
    out_pos = args.output_plot.with_name(args.output_plot.stem + "_pos" + args.output_plot.suffix)
    out_neg = args.output_plot.with_name(args.output_plot.stem + "_neg" + args.output_plot.suffix)

    plot_summary(summary, out_overall, title + " (overall)")
    plot_summary(summary_pos, out_pos, title + " (positive pairs)")
    plot_summary(summary_neg, out_neg, title + " (negative pairs)")

    print(f"Saved plots to: {out_overall}, {out_pos}, {out_neg}")


if __name__ == "__main__":
    main()